version: "3"

services:
  strapiexample:
    image: strapi/strapi
    container_name: strapiexample
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: blogapi_prod
      DATABASE_HOST: strapi_db
      DATABASE_PORT: 5432
      DATABASE_USERNAME: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    #    links:
    #      - mongo:mongo
    networks:
      - strapi-app-network
    volumes:
      - ./no-ghosts-api:/srv/app
    ports:
      - "1337:1337"

  strapi_db:
    container_name: strapi_db
    image: postgres:13.0
    restart: always
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - db-data0:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
    networks:
      - strapi-app-network

networks:
  strapi-app-network:
    driver: bridge

volumes:
  db-data0:
